### ISSUE TITLE
Stopped working 

### ISSUE THREAD

**Issue by krazykoder** [yahoofinancelive/yliveticker#10]
Seems like this library stopped working. I am not sure if this is python version or changes in the data format. Can you please help. Do you see similar issues. 
I am using python 3.8.

**Comment by alparamonov** [comment]
I'm looking into it. Do you get any errors?

**Comment by krazykoder** [comment]
No errors. Just blank - no output.

**Comment by alparamonov** [comment]
Fixed in new release v0.2.8. Update the package and feel free to reopen the issue if the problem persists.

**Comment by krazykoder** [comment]
Still not working. I do get the message "### connection is open ###" but no updates after that. Details below

`(venv3) ~/code/python/pythonic/compilation$ python -V
Python 3.8.0
(venv3) ~/code/python/pythonic/compilation$ pip list | grep live
yflive                0.1.2
yliveticker           0.2.8
(venv3) ~/code/python/pythonic/compilation$ python liveTICK.py
### connection is open ###

`

The code is same as you posted in examples: 

`import yliveticker

# this function is called on each ticker update
def on_new_msg(msg):
#   print ("Hello")
    print(msg)

yliveticker.YLiveTicker(on_ticker=on_new_msg, ticker_names=["AAPL", "AMZN", "AMAT"])
`

**Comment by alparamonov** [comment]
@krazykoder thanks for posting. The issue was no longer with the package itself, but with the example in readme. Please, check the new [client code](https://github.com/yahoofinancelive/yliveticker/blob/master/yliveticker/client_code.py) or [readme example](https://github.com/yahoofinancelive/yliveticker/blob/master/README.md).

So, instead of the old code snippet, use this:
```python
import yliveticker


# this function is called on each ticker update
def on_new_msg(ws, msg):
    print(msg)


yliveticker.YLiveTicker(on_ticker=on_new_msg, ticker_names=[
    "BTC=X", "^GSPC", "^DJI", "^IXIC", "^RUT", "CL=F", "GC=F", "SI=F", "EURUSD=X", "^TNX", "^VIX", "GBPUSD=X", "JPY=X", "BTC-USD", "^CMC200", "^FTSE", "^N225"])
```

And also don't forget to update to v0.2.9

`pip install yliveticker==0.2.9`

Please, let me know if it worked for you.

**Comment by krazykoder** [comment]
It worked. thanks for help me out. Appreciate it.
