### ISSUE TITLE
Need help to use the output of yliveticker and save to database

### ISSUE THREAD

**Issue by vishvesh098** [yahoofinancelive/yliveticker#11]
**Subject**
I need some help on how to use the output of yliveticker and save to database

**Question**
First of all @alparamonov you have done a fantastic job by creating this tool ! I have tested it and it works good. But my question are ...

1) When I use the yliveticker the python code is stuck reading it, means it dont go to the next line. As yliveticker is contunously streaming data, how can i store it to sqlite db ? (means code is just executing on yliveticker it wont going ahead)

2) I have observed that when I use multiple tickers like 30-50 some ticks may be missing. i.e. on my test single ticker gave me approx 1-4 tick per sec and multiple ticker (like 30-50) might missing some of the ticks on same time window. Did you encountered this issue ? (I am using all F&O Tickers of NSE - Indian Stock Market)

3) I need your suggestion, I am planning to build an alert system and finally make it to full fledged algo system. Can I use yliveticker in Async or lets say concurrently ? ( I am very new to python !) my plan is as under.
                                          
                                          Ticker_1                              Ticker_2                              Ticker_3            And so on upto 160 Tickers
                                             |                                          |                                          |            
                                          Get live Data                    Get Live Data                     Get Live Data      
                                             |                                          |                                          |            
                                          Store to DB                    Store to DB                           Store to DB
                                             |                                          |                                          |            
                                          Build OHLCV (5min)         Build OHLCV (5min)          Build OHLCV (5min)
                                             |                                          |                                          |            
                                          Tech. Analysis                 Tech. Analysis                      Tech. Analysis
                                             |                                          |                                          |            
                                          Get Alert                         Get Alert                               Get Alert

I am planning to complete all of the above tasks in approx 1-2 seconds. If 160 Tickers at one take time then I make different files each to running 30 or 40 or 50 tickers.

Can you guide me to help yliveticker with async or whatever is required for working simultaneously ?

As of now I tried using yahooquery and sqlite3 to make simple database system. But now i want to use live streaming of data using your application.

Eagerly waiting for your reply !

Thanks & Regards,
Vishvesh Upadhyay.

**Comment by alparamonov** [comment]
Hi Vishvesh, great to hear that you find this package useful! Your contributions in any form, from posting improvement suggestions to submitting a pull request are always appreciated.

> When I use the yliveticker the python code is stuck reading it, means it dont go to the next line. As yliveticker is contunously streaming data, how can i store it to sqlite db ? (means code is just executing on yliveticker it wont going ahead)

I'm not quite sure how you use it. It'd help if you could post your code snippet. In general, refer to the example in readme.
```python
def on_new_msg(ws, msg):
    print(msg)
```
This function is called when new chunk of data arrives. You can put your db inserts instead of `print(msg)`. Also, consider stream-based architectures and time series dbs as you are constantly reading from the stream here.

> I have observed that when I use multiple tickers like 30-50 some ticks may be missing. i.e. on my test single ticker gave me approx 1-4 tick per sec and multiple ticker (like 30-50) might missing some of the ticks on same time window. Did you encountered this issue ? (I am using all F&O Tickers of NSE - Indian Stock Market)

Be mindful and gentle to yahoo infrastructure. As other tested it out, the API throttles you if you are reading tens of tickers simultaneously. Other data peculiarities also relate to external factors ranging from how the data comes from the market to yahoo systems, to how the API serves you for a particular ticker in particular time, and location. We can't control or change this. Instead, think about how critical it is for you to never miss any data. Often times, you can either interpolate, or just move on in your analysis with missing values.

> I need your suggestion, I am planning to build an alert system and finally make it to full fledged algo system. Can I use yliveticker in Async or lets say concurrently ? ( I am very new to python !) my plan is as under.

yliveticker doesn't support multithreading out of the box. PRs are very welcome ;) What you can do is to start multiple instances of your application and write an extra service coordinate those instances. Think of microservices/distributed systems.

Let me know if you have any further questions.

**Comment by vishvesh098** [comment]
Thank you for such quick response ! I will definitely look into it and try to build further on your suggestion !
